version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: "fa6a83f203cb81046eab607216bf8ca3e54b62c19805bb365ebe77fe6e69130f"
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    working_directory: ~/never_alone_be
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: gem install bundler:2.1.4
      - ruby/bundle-install
      - run:
          name: Database setup
          command: |
            bin/rails db:setup
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: |
            bundle exec rspec